sudo: required
dist: trusty
services:
  - docker

language: go

addons:
  apt:
    packages:
      - python-virtualenv

env:
  matrix:
    - TARGETS="check"
    - TARGETS="testsuite"
    - TARGETS="crosscompile"
  global:
    - DOCKER_COMPOSE_VERSION: 1.7.0

script: make $TARGETS

install: go get -t ./...

go:
  - 1.5.1
  - tip
