language: go

addons:
  apt:
    packages:
      - python-virtualenv

env:
  matrix:
    - TARGETS="check"
    - TARGETS="testsuite"
    - TARGETS="crosscompile"

script: make $TARGETS

install: go get -t ./...

go:
  - 1.5.1
  - tip
